if (NOT TARGET libavformat)
    message(STATUS "    Creating target: libavformat")
    add_library(libavformat OBJECT ${AVFORMAT_LIBRARIES})
    target_link_libraries(libavformat ${AVFORMAT_LIBRARIES})
    set_target_properties(libavformat PROPERTIES LINKER_LANGUAGE CXX)
    # set the target's folder (for IDEs that support it, e.g. Visual Studio)
    set_target_properties(libavformat PROPERTIES FOLDER "FFMPEG-LIBS")
    if (OS_TARGET STREQUAL win)
        ffmpeg_query_wildcard(${AVFORMAT_LIBRARIES} avformat*.dll DLL_FILE)
        ffmpeg_copy_dll_after_build(libavformat ${DLL_FILE})
    endif()
    #include_directories(${AVFORMAT_INCLUDE_DIR})
endif()