if (NOT TARGET libavdevice)
    message(STATUS "    Creating target: libavdevice")
    add_library(libavdevice OBJECT ${AVDEVICE_LIBRARIES})
    target_link_libraries(libavdevice ${AVDEVICE_LIBRARIES})
    set_target_properties(libavdevice PROPERTIES LINKER_LANGUAGE CXX)
    # set the target's folder (for IDEs that support it, e.g. Visual Studio)
    set_target_properties(libavdevice PROPERTIES FOLDER "FFMPEG-LIBS")
    if (OS_TARGET STREQUAL win)
        ffmpeg_query_wildcard(${AVDEVICE_LIBRARIES} avdevice*.dll DLL_FILE)
        ffmpeg_copy_dll_after_build(libavdevice ${DLL_FILE})
    endif()
    #include_directories(${AVDEVICE_INCLUDE_DIR})
endif()