if (NOT TARGET libavfilter)
    message(STATUS "    Creating target: libavfilter")
    add_library(libavfilter OBJECT ${AVFILTER_LIBRARIES})
    target_link_libraries(libavfilter ${AVFILTER_LIBRARIES})
    set_target_properties(libavfilter PROPERTIES LINKER_LANGUAGE CXX)
    # set the target's folder (for IDEs that support it, e.g. Visual Studio)
    set_target_properties(libavfilter PROPERTIES FOLDER "FFMPEG-LIBS")
    if (OS_TARGET STREQUAL win)
        ffmpeg_query_wildcard(${AVFILTER_LIBRARIES} avfilter*.dll DLL_FILE)
        ffmpeg_copy_dll_after_build(libavfilter ${DLL_FILE})
    endif()
    #include_directories(${AVFILTER_INCLUDE_DIR})
endif()