if (NOT TARGET libavutil)
    message(STATUS "    Creating target: libavutil")
    add_library(libavutil OBJECT ${AVUTIL_LIBRARIES})
    target_link_libraries(libavutil ${AVUTIL_LIBRARIES})
    set_target_properties(libavutil PROPERTIES LINKER_LANGUAGE CXX)
    # set the target's folder (for IDEs that support it, e.g. Visual Studio)
    set_target_properties(libavutil PROPERTIES FOLDER "FFMPEG-LIBS")
    if (OS_TARGET STREQUAL win)
        ffmpeg_query_wildcard(${AVUTIL_LIBRARIES} avutil*.dll DLL_FILE)
        ffmpeg_copy_dll_after_build(libavutil ${DLL_FILE})
    endif()
    #include_directories(${AVUTIL_INCLUDE_DIR})
endif()