if (NOT TARGET libpostproc)
    message(STATUS "    Creating target: libpostproc")
    add_library(libpostproc OBJECT ${POSTPROC_LIBRARIES})
    target_link_libraries(libpostproc ${POSTPROC_LIBRARIES})
    set_target_properties(libpostproc PROPERTIES LINKER_LANGUAGE CXX)
    # set the target's folder (for IDEs that support it, e.g. Visual Studio)
    set_target_properties(libpostproc PROPERTIES FOLDER "FFMPEG-LIBS")
    if (WIN32)
        ffmpeg_query_wildcard(${POSTPROC_LIBRARIES} postproc*.dll DLL_FILE)
        ffmpeg_copy_dll_after_build(libpostproc ${DLL_FILE})
    elseif (APPLE)
        ffmpeg_query_wildcard(${POSTPROC_LIBRARIES} libpostproc*.dylib DYN_LIB)
        get_filename_component(DYN_LIB_NAME ${DYN_LIB} NAME)
        configure_file("${DYN_LIB}" "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${DYN_LIB_NAME}" COPYONLY)
    endif()
    #include_directories(${POSTPROC_INCLUDE_DIR})
endif()