if (NOT TARGET libswresample)
    message(STATUS "    Creating target: libswresample")
    add_library(libswresample OBJECT ${SWRESAMPLE_LIBRARIES})
    target_link_libraries(libswresample ${SWRESAMPLE_LIBRARIES})
    set_target_properties(libswresample PROPERTIES LINKER_LANGUAGE CXX)
    # set the target's folder (for IDEs that support it, e.g. Visual Studio)
    set_target_properties(libswresample PROPERTIES FOLDER "FFMPEG-LIBS")
    if (OS_TARGET STREQUAL win)
        ffmpeg_query_wildcard(${SWRESAMPLE_LIBRARIES} swresample*.dll DLL_FILE)
        ffmpeg_copy_dll_after_build(libswresample ${DLL_FILE})
    endif()
    #include_directories(${SWRESAMPLE_INCLUDE_DIR})
endif()